// crud 配置文件 - Ant Design Vue 版本
export default {
  menuWidth: 220,
  menuFixed: 'right',
  menuXsWidth: 100,
  menuAlign: 'center',
  menuHeaderAlign: 'center',
  headerAlign: 'left',

  // 图标 - Ant Design Icons
  cancelBtnIcon: 'close-circle',
  viewBtnIcon: 'eye',
  editBtnIcon: 'edit',
  copyBtnIcon: 'copy',
  addBtnIcon: 'plus',
  printBtnIcon: 'printer',
  mockBtnIcon: 'edit',
  excelBtnIcon: 'download',
  delBtnIcon: 'delete',
  searchBtnIcon: 'search',
  emptyBtnIcon: 'delete',
  saveBtnIcon: 'plus-circle',
  updateBtnIcon: 'check-circle',
  columnBtnIcon: 'setting',
  filterBtnIcon: 'filter',
  gridBtnIcon: 'appstore',
  refreshBtnIcon: 'reload',

  // 显隐
  viewBtn: false,
  editBtn: true,
  copyBtn: false,
  cancelBtn: true,
  addBtn: true,
  addRowBtn: false,
  printBtn: false,
  mockBtn: false,
  excelBtn: false,
  delBtn: true,
  cellBtn: false,
  dateBtn: false,
  updateBtn: true,
  saveBtn: true,
  refreshBtn: true,
  columnBtn: true,
  filterBtn: false,
  gridBtn: true,
  queryBtn: true,
  menuBtn: false,
  searchBtn: true,
  clearBtn: true,
  selectClearBtn: true,
  searchShow: true,
  tip: true,
  dialogWidth: '60%',
  dialogDrag: false,
  formFullscreen: false,
  pageBackground: true,
  page: true,
  menu: true,
  indexLabel: '#',
  indexWidth: 50,
  indexFixed: 'left',
  selectionWidth: 50,
  selectionFixed: 'left',
  expandWidth: 60,
  expandFixed: 'left',
  filterMultiple: true,
  calcHeight: 300,
  width: '100%',
  searchLabelWidth: 80,
  searchSpan: 6,
  dropRowClass: '.ant-table-tbody',
  dropColClass: '.ant-table-thead > tr',
  ghostClass: 'tvue-crud__ghost',
};
